import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const CV_DIR = join(process.cwd(), "public", "cv");
const OUTPUT = join(process.cwd(), "src", "data", "cv-manifest.ts");

const LANGUAGE_MAP: Record<string, string> = {
  "pt-br": "Portugues",
  pt: "Portugues",
  en: "English",
  es: "Espanol",
  fr: "Frances",
  de: "Alemao",
  it: "Italiano",
  ja: "日本語",
  zh: "中文",
};

function deriveLabel(filename: string): string {
  const lower = filename.toLowerCase();
  for (const [code, label] of Object.entries(LANGUAGE_MAP)) {
    if (lower.includes(code)) return label;
  }
  return filename.replace(/\.pdf$/i, "");
}

const files = readdirSync(CV_DIR)
  .filter((f) => f.toLowerCase().endsWith(".pdf"))
  .sort();

const manifest = files.map((filename) => ({
  path: `/cv/${filename}`,
  label: deriveLabel(filename),
}));

mkdirSync(dirname(OUTPUT), { recursive: true });

const code = `// AUTO-GENERATED by scripts/generate-cv-manifest.ts
// Nao editar manualmente. Regenerado a cada dev/build a partir de public/cv/.

export interface CvEntry {
  path: string;
  label: string;
}

export const CV_MANIFEST: CvEntry[] = ${JSON.stringify(manifest, null, 2)};
`;

writeFileSync(OUTPUT, code);
console.log(`[cv-manifest] ${manifest.length} arquivo(s) encontrado(s) em public/cv/`);
