// AUTO-GENERATED by scripts/generate-cv-manifest.ts
// Nao editar manualmente. Regenerado a cada dev/build a partir de public/cv/.

export interface CvEntry {
  path: string;
  label: string;
}

export const CV_MANIFEST: CvEntry[] = [
  {
    "path": "/cv/Fernando_Moreira_Fullstack_EN.pdf",
    "label": "English"
  },
  {
    "path": "/cv/Fernando_Moreira_Fullstack_PT-BR.pdf",
    "label": "Portugues"
  }
];
